[package]
name = "confsync"
version = "0.1.0"
edition = "2021"
[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
chrono = "0.4"
directories = "6.0.0"
git2 = "0.20.1"
serde = {version = "1.0", features = ["derive"]}
toml = "0.8"
